<a href="https://colab.research.google.com/github/Emmy16ie/Machine-Learning/blob/main/CarlifoniaHousing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install fastapi[standard] joblib

Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (1.6.0)
Requirement already satisfied: fastapi[standard] in /usr/local/lib/python3.13/dist-packages (0.141.1)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from fastapi[standard]) (1.7.0)
Requirement already satisfied: pydantic>=2.9.0 in /usr/local/lib/python3.13/dist-packages (from fastapi[standard]) (2.13.5)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.13/dist-packages (from fastapi[standard]) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from fastapi[standard]) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from fastapi[standard]) (0.0.5)
Collecting fastapi-cli>=0.0.32 (from fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard])
  Downloading fastapi_cli-0.0.32-py3-none-any.whl.metadata (6.7 kB)
Collecting fastar>=0.9.0 (from fastapi[standard])
  Downloading fastar-0.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from fastapi[standard]) (0.28.1)
Requirement already satisfied: jinja2>=3.1.5 in /usr/local/lib/python3.13/dist-packages (from fastapi[standard]) (3.1.6)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.13/dist-packages (from fastapi[standard]) (0.0.32)
Collecting email-validator>=2.0.0 (from fastapi[standard])
  Downloading email_validator-2.3.0-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: uvicorn>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]) (0.54.0)
Collecting pydantic-settings>=2.0.0 (from fastapi[standard])
  Downloading pydantic_settings-2.15.0-py3-none-any.whl.metadata (3.9 kB)
Collecting pydantic-extra-types>=2.0.0 (from fastapi[standard])
  Downloading pydantic_extra_types-2.11.1-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib) (3.1.2)
Collecting dnspython>=2.0.0 (from email-validator>=2.0.0->fastapi[standard])
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: idna>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from email-validator>=2.0.0->fastapi[standard]) (3.20)
Requirement already satisfied: typer>=0.16.0 in /usr/local/lib/python3.13/dist-packages (from fastapi-cli>=0.0.32->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard]) (0.27.2)
Collecting rich-toolkit>=0.14.8 (from fastapi-cli>=0.0.32->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard])
  Downloading rich_toolkit-0.20.5-py3-none-any.whl.metadata (3.0 kB)
Collecting fastapi-cloud-cli>=0.1.1 (from fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard])
  Downloading fastapi_cloud_cli-0.26.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->fastapi[standard]) (4.15.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->fastapi[standard]) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0,>=0.23.0->fastapi[standard]) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->fastapi[standard]) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2>=3.1.5->fastapi[standard]) (3.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9.0->fastapi[standard]) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9.0->fastapi[standard]) (2.46.5)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.13/dist-packages (from pydantic-settings>=2.0.0->fastapi[standard]) (1.2.3)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn>=0.12.0->uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]) (8.5.0)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]) (0.8.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]) (6.0.3)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]) (1.3.0)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.13/dist-packages (from uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]) (15.0.1)
Collecting rignore>=0.5.1 (from fastapi-cloud-cli>=0.1.1->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard])
  Downloading rignore-0.8.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: sentry-sdk>=2.20.0 in /usr/local/lib/python3.13/dist-packages (from fastapi-cloud-cli>=0.1.1->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard]) (2.71.0)
Collecting detect-installer>=0.1.0 (from fastapi-cloud-cli>=0.1.1->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard])
  Downloading detect_installer-0.2.1-py3-none-any.whl.metadata (1.2 kB)
Collecting agent-detector>=1.1.0 (from fastapi-cloud-cli>=0.1.1->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard])
  Downloading agent_detector-2.0.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: rich>=13.7.1 in /usr/local/lib/python3.13/dist-packages (from rich-toolkit>=0.14.8->fastapi-cli>=0.0.32->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard]) (13.9.4)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer>=0.16.0->fastapi-cli>=0.0.32->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard]) (1.5.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.7.1->rich-toolkit>=0.14.8->fastapi-cli>=0.0.32->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.7.1->rich-toolkit>=0.14.8->fastapi-cli>=0.0.32->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard]) (2.21.0)
Requirement already satisfied: urllib3>=1.26.11 in /usr/local/lib/python3.13/dist-packages (from sentry-sdk>=2.20.0->fastapi-cloud-cli>=0.1.1->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard]) (2.5.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.7.1->rich-toolkit>=0.14.8->fastapi-cli>=0.0.32->fastapi-cli[standard]>=0.0.32; extra == "standard"->fastapi[standard]) (0.1.2)
Downloading email_validator-2.3.0-py3-none-any.whl (35 kB)
Downloading fastapi_cli-0.0.32-py3-none-any.whl (14 kB)
Downloading fastar-0.12.0-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (807 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.6/807.6 kB 4.7 MB/s eta 0:00:00
Downloading pydantic_extra_types-2.11.1-py3-none-any.whl (79 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 6.4 MB/s eta 0:00:00
Downloading pydantic_settings-2.15.0-py3-none-any.whl (69 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 5.3 MB/s eta 0:00:00
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 19.5 MB/s eta 0:00:00
Downloading fastapi_cloud_cli-0.26.0-py3-none-any.whl (108 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.7/108.7 kB 9.0 MB/s eta 0:00:00
Downloading rich_toolkit-0.20.5-py3-none-any.whl (39 kB)
Downloading agent_detector-2.0.0-py3-none-any.whl (9.4 kB)
Downloading detect_installer-0.2.1-py3-none-any.whl (5.4 kB)
Downloading rignore-0.8.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (928 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 928.0/928.0 kB 14.2 MB/s eta 0:00:00
Installing collected packages: rignore, fastar, dnspython, detect-installer, agent-detector, email-validator, rich-toolkit, pydantic-settings, pydantic-extra-types, fastapi-cloud-cli, fastapi-cli
Successfully installed agent-detector-2.0.0 detect-installer-0.2.1 dnspython-2.8.0 email-validator-2.3.0 fastapi-cli-0.0.32 fastapi-cloud-cli-0.26.0 fastar-0.12.0 pydantic-extra-types-2.11.1 pydantic-settings-2.15.0 rich-toolkit-0.20.5 rignore-0.8.1

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import joblib

In [3]:
from sklearn.datasets import fetch_california_housing

In [4]:
from fastapi import FastAPI
from pydantic import BaseModel
import joblib

In [5]:
data = fetch_california_housing(as_frame=True)

X = data.data
y = data.target

In [6]:
X.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [7]:
print(X.shape)
print(X.columns)
print(y.head())

(20640, 8)
Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude'],
      dtype='object')
0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: MedHouseVal, dtype: float64

In [8]:
X.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state = 42)

In [10]:
print("Training size: ", X_train.size)
print("Testing size: ", X_test.size)

Training size:  132096
Testing size:  33024

In [11]:
model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

In [12]:
y_pred = model.predict(X_test)

In [13]:
print(y_pred[:5])

[0.71912284 1.76401657 2.70965883 2.83892593 2.60465725]

In [14]:
print(y_test[:5])

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
Name: MedHouseVal, dtype: float64

In [16]:
#Mathematical Model representation

print("Weigths: " , model.coef_)
print("Bias: ", model.intercept_)

Weigths:  [ 4.48674910e-01  9.72425752e-03 -1.23323343e-01  7.83144907e-01
 -2.02962058e-06 -3.52631849e-03 -4.19792487e-01 -4.33708065e-01]
Bias:  -37.02327770606409

In [18]:
data.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [19]:
X_test[:5]

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
20046,1.6812,25.0,4.192201,1.022284,1392.0,3.877437,36.06,-119.01
3024,2.5313,30.0,5.039384,1.193493,1565.0,2.679795,35.14,-119.46
15663,3.4801,52.0,3.977155,1.185877,1310.0,1.360332,37.80,-122.44
20484,5.7376,17.0,6.163636,1.020202,1705.0,3.444444,34.28,-118.72
9814,3.7250,34.0,5.492991,1.028037,1063.0,2.483645,36.62,-121.93

In [20]:
y_test[:5]

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
Name: MedHouseVal, dtype: float64

In [37]:
# Weights
w = model.coef_
w_t = w.T

print(w_t)

[ 4.48674910e-01  9.72425752e-03 -1.23323343e-01  7.83144907e-01
 -2.02962058e-06 -3.52631849e-03 -4.19792487e-01 -4.33708065e-01]

In [38]:
# Bias
bias = model.intercept_

print(bias)

-37.02327770606409

In [41]:
# Test input test_row(x) = col_matrix(x1-x8)
test_row = X_test.iloc[4].to_numpy()

print(test_row)

[ 3.72500000e+00  3.40000000e+01  5.49299065e+00  1.02803738e+00
  1.06300000e+03  2.48364486e+00  3.66200000e+01 -1.21930000e+02]

In [46]:
test_y = np.dot(w_t, test_row) + bias

print(test_y)

2.604657251810295

In [47]:
print(np.dot(w_t, test_row))

39.62793495787439

In [48]:
joblib.dump(model, 'house_price_model.pkl')

['house_price_model.pkl']

In [49]:
!ls

house_price_model.pkl  sample_data